language: node_js
node_js:
  - stable
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode8.2
      before_install:
        - nvm install 7
        - node --version
      install:
        - travis_retry gem install xcpretty
        - npm install
      xcode_project: ios/poopr.xcodeproj
      xcode_scheme: ios/poopr
      script:
        - cd ios
        - xcodebuild -scheme poopr -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - npm test